version: '3.8'

services:
  backend:
    build:
      context: ./backend
      # context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./backend/.env

  db:
    image: postgres:13
    restart: always
    container_name: projeto-integrador-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    env_file:
      - ./backend/.env
  
  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      platform: linux/amd64
      ports:
        - "8080:80"
      depends_on:
        - backend


volumes:
  db_data: